"""Tests for :mod:`grasp.gaia.query`.

Covers a mix of mocked calls (to avoid hitting the real Gaia TAP service) and
purely string-level checks of the ADQL command generated by
:class:`grasp.gaia.query.GaiaQuery`.
"""

import unittest
from unittest.mock import MagicMock, patch

from astropy.table import QTable

from grasp._utility.cluster import Cluster
from grasp.gaia.query import GaiaQuery, _split_gaia_table


class TestGaiaQuery(unittest.TestCase):
    def setUp(self):
        self.gaia_query = GaiaQuery()

    def test_initialization(self):
        self.assertEqual(self.gaia_query._table, "gaiadr3.gaia_source")

    @patch("grasp.gaia.query.GaiaQuery._run_query")
    def test_free_gc_query(self, mock_run_query):
        mock_run_query.return_value = QTable({"col1": [1, 2], "col2": [3, 4]})
        cluster = Cluster("ngc104")
        result = self.gaia_query.free_gc_query(0.1, gc=cluster)
        self.assertIsNotNone(result)
        mock_run_query.assert_called_once()

    @patch("grasp.gaia.query.GaiaQuery._run_query")
    def test_get_astrometry(self, mock_run_query):
        mock_run_query.return_value = QTable({"col1": [1, 2], "col2": [3, 4]})
        cluster = Cluster("ngc104")
        result = self.gaia_query.get_astrometry(0.1, gc=cluster)
        self.assertIsNotNone(result)
        mock_run_query.assert_called_once()

    @patch("grasp.gaia.query.GaiaQuery._run_query")
    def test_get_photometry(self, mock_run_query):
        mock_run_query.return_value = QTable({"col1": [1, 2], "col2": [3, 4]})
        cluster = Cluster("ngc104")
        result = self.gaia_query.get_photometry(0.1, gc=cluster)
        self.assertIsNotNone(result)
        mock_run_query.assert_called_once()

    @patch("grasp.gaia.query.GaiaQuery._run_query")
    def test_get_rv(self, mock_run_query):
        mock_run_query.return_value = QTable({"col1": [1, 2], "col2": [3, 4]})
        cluster = Cluster("ngc104")
        result = self.gaia_query.get_rv(0.1, gc=cluster)
        self.assertIsNotNone(result)
        mock_run_query.assert_called_once()

    @patch("grasp.gaia.query._Gaia.launch_job_async")
    def test_free_query_uses_provided_adql(self, mock_launch):
        """``free_query`` accepts a raw ADQL string and should pass it through."""
        mock_job = MagicMock()
        mock_job.get_results.return_value = QTable({"source_id": [1, 2]})
        mock_launch.return_value = mock_job

        adql = (
            "SELECT source_id, ra, dec FROM gaiadr3.gaia_source "
            "WHERE CONTAINS(POINT('ICRS', ra, dec),"
            " CIRCLE('ICRS', 10.0, 20.0, 0.1)) = 1"
        )
        result = self.gaia_query.free_query(adql)

        self.assertIsNotNone(result)
        mock_launch.assert_called_once()
        sent_query = mock_launch.call_args.args[0]
        self.assertEqual(sent_query, adql)
        self.assertIn("CIRCLE('ICRS', 10.0, 20.0, 0.1)", sent_query)
        self.assertEqual(
            self.gaia_query._queryInfo["Scan_Info"]["Command"], adql
        )


class TestSplitGaiaTable(unittest.TestCase):
    def test_qualified_dr3(self):
        self.assertEqual(_split_gaia_table("gaiadr3.gaia_source"), ("gaiadr3", "gaia_source"))

    def test_qualified_dr2(self):
        self.assertEqual(_split_gaia_table("gaiadr2.gaia_source"), ("gaiadr2", "gaia_source"))

    def test_unqualified(self):
        self.assertEqual(_split_gaia_table("gaia_source"), ("gaiadr3", "gaia_source"))

    def test_none(self):
        self.assertEqual(_split_gaia_table(None), ("gaiadr3", "gaia_source"))

    def test_list_uses_first(self):
        self.assertEqual(
            _split_gaia_table(["gaiadr2.gaia_source", "gaiadr3.gaia_source"]),
            ("gaiadr2", "gaia_source"),
        )


class TestAdqlWriterQualifier(unittest.TestCase):
    """Regression tests for P1-1: schema-qualified coordinates in ADQL.

    Previously ``GaiaQuery._adqlWriter`` hard-coded ``gaiadr3.gaia_source.ra``
    even when the user had initialised the class against a different Gaia
    table (e.g. ``gaiadr2.gaia_source``). These tests guarantee that the
    qualifier matches whatever release was selected and that DR3 references
    never leak into a DR2 query.
    """

    def test_dr2_qualifier_is_emitted(self):
        gq = GaiaQuery(gaia_table="gaiadr2.gaia_source")
        query = gq._adqlWriter(
            ra=10.0,
            dec=20.0,
            radius=0.1,
            data="source_id, ra, dec",
            conditions="None",
        )
        self.assertIn("gaiadr2.gaia_source.ra", query)
        self.assertIn("gaiadr2.gaia_source.dec", query)
        self.assertNotIn("gaiadr3.gaia_source.ra", query)
        self.assertNotIn("gaiadr3.gaia_source.dec", query)
        self.assertIn("FROM gaiadr2.gaia_source", query)

    def test_dr3_qualifier_is_emitted(self):
        gq = GaiaQuery(gaia_table="gaiadr3.gaia_source")
        query = gq._adqlWriter(
            ra=10.0,
            dec=20.0,
            radius=0.1,
            data="source_id",
            conditions="None",
        )
        self.assertIn("gaiadr3.gaia_source.ra", query)
        self.assertIn("gaiadr3.gaia_source.dec", query)
        self.assertNotIn("gaiadr2.gaia_source.ra", query)

    def test_circle_has_four_arguments(self):
        """ADQL ``CIRCLE`` is ``CIRCLE('frame', ra, dec, radius)`` (arity 4)."""
        gq = GaiaQuery(gaia_table="gaiadr3.gaia_source")
        query = gq._adqlWriter(
            ra=10.0,
            dec=20.0,
            radius=0.1,
            data="source_id",
            conditions="None",
        )
        self.assertIn("CIRCLE('ICRS', 10.0, 20.0, 0.100)", query)

    def test_unqualified_coords_optional(self):
        gq = GaiaQuery(gaia_table="gaiadr2.gaia_source")
        query = gq._adqlWriter(
            ra=10.0,
            dec=20.0,
            radius=0.1,
            data="source_id",
            conditions="None",
            qualified_coords=False,
        )
        self.assertIn("POINT('ICRS', ra, dec)", query)
        self.assertNotIn("gaiadr2.gaia_source.ra", query)


if __name__ == "__main__":
    unittest.main()
