"""Tests for :mod:`grasp.gaia.query`.

Covers a mix of mocked calls (to avoid hitting the real Gaia TAP service) and
purely string-level checks of the ADQL command generated by
:class:`grasp.gaia.query.GaiaQuery`.
"""

import unittest
from unittest.mock import patch, MagicMock
from astropy.table import QTable

from grasp.gaia.query import GaiaQuery
from grasp._utility.cluster import Cluster


class TestGaiaQuery(unittest.TestCase):
    def setUp(self):
        self.gaia_query = GaiaQuery()

    def test_initialization(self):
        self.assertEqual(self.gaia_query._table, "gaiadr3.gaia_source")

    @patch("grasp.gaia.query.GaiaQuery._run_query")
    def test_free_gc_query(self, mock_run_query):
        mock_run_query.return_value = QTable({"col1": [1, 2], "col2": [3, 4]})
        cluster = Cluster("ngc104")
        result = self.gaia_query.free_gc_query(0.1, gc=cluster)
        self.assertIsNotNone(result)
        mock_run_query.assert_called_once()

    @patch("grasp.gaia.query.GaiaQuery._run_query")
    def test_get_astrometry(self, mock_run_query):
        mock_run_query.return_value = QTable({"col1": [1, 2], "col2": [3, 4]})
        cluster = Cluster("ngc104")
        result = self.gaia_query.get_astrometry(0.1, gc=cluster)
        self.assertIsNotNone(result)
        mock_run_query.assert_called_once()

    @patch("grasp.gaia.query.GaiaQuery._run_query")
    def test_get_photometry(self, mock_run_query):
        mock_run_query.return_value = QTable({"col1": [1, 2], "col2": [3, 4]})
        cluster = Cluster("ngc104")
        result = self.gaia_query.get_photometry(0.1, gc=cluster)
        self.assertIsNotNone(result)
        mock_run_query.assert_called_once()

    @patch("grasp.gaia.query.GaiaQuery._run_query")
    def test_get_rv(self, mock_run_query):
        mock_run_query.return_value = QTable({"col1": [1, 2], "col2": [3, 4]})
        cluster = Cluster("ngc104")
        result = self.gaia_query.get_rv(0.1, gc=cluster)
        self.assertIsNotNone(result)
        mock_run_query.assert_called_once()

    @patch("grasp.gaia.query._Gaia.launch_job_async")
    def test_free_query_uses_provided_adql(self, mock_launch):
        """``free_query`` accepts a raw ADQL string and should pass it through."""
        mock_job = MagicMock()
        mock_job.get_results.return_value = QTable({"source_id": [1, 2]})
        mock_launch.return_value = mock_job

        adql = (
            "SELECT source_id, ra, dec FROM gaiadr3.gaia_source "
            "WHERE CONTAINS(POINT('ICRS', ra, dec),"
            " CIRCLE('ICRS', 10.0, 20.0, 0.1)) = 1"
        )
        result = self.gaia_query.free_query(adql)

        self.assertIsNotNone(result)
        mock_launch.assert_called_once()
        sent_query = mock_launch.call_args.args[0]
        self.assertEqual(sent_query, adql)
        self.assertIn("CIRCLE('ICRS', 10.0, 20.0, 0.1)", sent_query)
        self.assertEqual(
            self.gaia_query._queryInfo["Scan_Info"]["Command"], adql
        )


if __name__ == "__main__":
    unittest.main()
